
@host={{$dotenv %LOADTESTSERVER}}
@svc=/pool

@authUrl={{$dotenv %XSUAA_AUTH_URL}}

###
# @name Token_Request
POST {{authUrl}}/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{$dotenv %XSUAA_CLIENT_ID}}
&client_secret={{$dotenv %XSUAA_CLIENT_SECRET}}


### Read pool without authorization
GET {{host}}{{svc}}/getInfo()


### Read pool with authorization
GET {{host}}{{svc}}/getInfo()
Authorization: Bearer {{Token_Request.response.body.access_token}}

